// AUTO-GENERATED by scaffold_config.py — review all fields before use
// Source: chicago-blackhawks-venue.json
// Fill in all STUB_ values before running node build.js

// ── TEAM IDENTITY ──────────────────────────────
const TEAM = {
  sport:           'nhl',
  orgName:         'Chicago Blackhawks',
  shortName:       'Blackhawks',
  logoFile:        'blackhawks-logo.png',
  stmLabel:        'Blackhawks Membership',
  ticketingVendor: 'Ticketmaster',
  scanVendor:      'Ticketmaster',
  fnbVendor:       'Levy Restaurants',
};

// ── BRAND ──────────────────────────────────────
const BRAND = {
  navy:        '#CF0A2C',
  navyMid:     '#f4183e',
  navySoft:    '#f7617b',
  navyPale:    '#faa0b0',
  navyGhost:   '#fdced6',
  accent:      '#000000',
  accentLight: '#f2f2f2',
  accentSoft:  'rgba(0,0,0,0.55)',
  accentRed:   '#D85F52',
  navyRgb:     '207,10,44',
};

// ── VENUE ──────────────────────────────────────
const VENUE = {
  name:     'United Center',
  capacity: 19717,
  sections: ["300 Level \u2013 Upper Bowl", "Standing Room Only", "200 Level \u2013 Lexus Club", "Handicap / ADA", "Banner Level Suites & Lofts", "100 Level \u2013 Lower Bowl"],
  sectionWeights: [100, 100, 100, 100, 100, 100],
  gates:    ["Gate 2", "Gate 3", "Gate 3\u00bd \u2013 American Express Entrance", "Gate 4 \u2013 Atrium", "Gate 5", "Gate 6", "Gate 6\u00bd \u2013 Suite VIP Entrance", "Gate 7", "Gate 8", "Gate 2\u00bd \u2013 Suite VIP Entrance"],
  gateBySectionWeights: {
    '300 Level – Upper Bowl': [4, 4, 3, 2, 2, 3, 1, 3, 1, 1],
    'Standing Room Only': [3, 3, 3, 2, 2, 3, 1, 3, 1, 1],
    '200 Level – Lexus Club': [3, 3, 2, 2, 2, 3, 2, 4, 1, 2],
    'Handicap / ADA': [2, 2, 2, 2, 2, 2, 1, 2, 1, 1],
    'Banner Level Suites & Lofts': [1, 1, 1, 1, 1, 1, 5, 1, 1, 5],
    '100 Level – Lower Bowl': [4, 3, 2, 3, 3, 4, 1, 4, 2, 1],
  },
};

// ── UPCOMING PACING ─── STUB: replace with current season data ──
const UPCOMING_PACING = [
  {
    "opponent": "Minnesota Wild",
    "date": "2026-05-06",
    "daysUntil": 2,
    "pctSold": 78
  },
  {
    "opponent": "St. Louis Blues",
    "date": "2026-05-08",
    "daysUntil": 4,
    "pctSold": 72
  },
  {
    "opponent": "Nashville Predators",
    "date": "2026-05-10",
    "daysUntil": 6,
    "pctSold": 69
  },
  {
    "opponent": "Detroit Red Wings",
    "date": "2026-05-13",
    "daysUntil": 9,
    "pctSold": 75
  },
  {
    "opponent": "Colorado Avalanche",
    "date": "2026-05-15",
    "daysUntil": 11,
    "pctSold": 82
  },
  {
    "opponent": "Winnipeg Jets",
    "date": "2026-05-17",
    "daysUntil": 13,
    "pctSold": 70
  },
  {
    "opponent": "Toronto Maple Leafs",
    "date": "2026-05-20",
    "daysUntil": 16,
    "pctSold": 88
  },
  {
    "opponent": "Dallas Stars",
    "date": "2026-05-22",
    "daysUntil": 18,
    "pctSold": 74
  },
  {
    "opponent": "Vancouver Canucks",
    "date": "2026-05-24",
    "daysUntil": 20,
    "pctSold": 68
  },
  {
    "opponent": "New York Rangers",
    "date": "2026-05-27",
    "daysUntil": 23,
    "pctSold": 85
  },
  {
    "opponent": "Pittsburgh Penguins",
    "date": "2026-05-29",
    "daysUntil": 25,
    "pctSold": 80
  },
  {
    "opponent": "Boston Bruins",
    "date": "2026-06-01",
    "daysUntil": 28,
    "pctSold": 83
  }
];

// ── SCHEDULE ─── STUB: replace with current season schedule ────
const SERIES_SCHEDULE = [
  {
    "start": "2025-10-11",
    "opp": "Detroit Red Wings",
    "lg": "Central",
    "rival": true,
    "n": 3,
    "tier": "featured",
    "promo": "giveaway",
    "promoLabel": "Opening Night Jersey Giveaway"
  },
  {
    "start": "2025-10-18",
    "opp": "Nashville Predators",
    "lg": "Central",
    "rival": false,
    "n": 1,
    "tier": "standard",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2025-10-25",
    "opp": "Minnesota Wild",
    "lg": "Central",
    "rival": false,
    "n": 1,
    "tier": "standard",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2025-11-01",
    "opp": "Toronto Maple Leafs",
    "lg": "Atlantic",
    "rival": true,
    "n": 2,
    "tier": "featured",
    "promo": "theme_night",
    "promoLabel": "Hockey Fights Cancer Night"
  },
  {
    "start": "2025-11-07",
    "opp": "Colorado Avalanche",
    "lg": "Central",
    "rival": false,
    "n": 1,
    "tier": "select",
    "promo": "giveaway",
    "promoLabel": "Bobblehead Giveaway"
  },
  {
    "start": "2025-11-14",
    "opp": "St. Louis Blues",
    "lg": "Central",
    "rival": true,
    "n": 3,
    "tier": "featured",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2025-11-22",
    "opp": "Winnipeg Jets",
    "lg": "Central",
    "rival": false,
    "n": 1,
    "tier": "standard",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2025-11-29",
    "opp": "Boston Bruins",
    "lg": "Atlantic",
    "rival": false,
    "n": 1,
    "tier": "select",
    "promo": "giveaway",
    "promoLabel": "Winter Classic Replica Jersey"
  },
  {
    "start": "2025-12-06",
    "opp": "New York Rangers",
    "lg": "Metropolitan",
    "rival": false,
    "n": 1,
    "tier": "select",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2025-12-13",
    "opp": "Dallas Stars",
    "lg": "Central",
    "rival": false,
    "n": 1,
    "tier": "standard",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2025-12-19",
    "opp": "Vegas Golden Knights",
    "lg": "Pacific",
    "rival": false,
    "n": 1,
    "tier": "select",
    "promo": "theme_night",
    "promoLabel": "Holiday Hat Giveaway"
  },
  {
    "start": "2025-12-27",
    "opp": "Minnesota Wild",
    "lg": "Central",
    "rival": false,
    "n": 2,
    "tier": "featured",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-01-03",
    "opp": "Pittsburgh Penguins",
    "lg": "Metropolitan",
    "rival": false,
    "n": 1,
    "tier": "standard",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-01-10",
    "opp": "Edmonton Oilers",
    "lg": "Pacific",
    "rival": false,
    "n": 1,
    "tier": "select",
    "promo": "giveaway",
    "promoLabel": "Scarf Giveaway"
  },
  {
    "start": "2026-01-17",
    "opp": "Anaheim Ducks",
    "lg": "Pacific",
    "rival": false,
    "n": 1,
    "tier": "standard",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-01-22",
    "opp": "Detroit Red Wings",
    "lg": "Atlantic",
    "rival": true,
    "n": 2,
    "tier": "featured",
    "promo": "theme_night",
    "promoLabel": "Alumni Night"
  },
  {
    "start": "2026-01-31",
    "opp": "Washington Capitals",
    "lg": "Metropolitan",
    "rival": false,
    "n": 1,
    "tier": "select",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-02-07",
    "opp": "Nashville Predators",
    "lg": "Central",
    "rival": false,
    "n": 2,
    "tier": "standard",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-02-14",
    "opp": "Vancouver Canucks",
    "lg": "Pacific",
    "rival": false,
    "n": 1,
    "tier": "standard",
    "promo": "theme_night",
    "promoLabel": "Valentine's Day Giveaway"
  },
  {
    "start": "2026-02-20",
    "opp": "St. Louis Blues",
    "lg": "Central",
    "rival": true,
    "n": 2,
    "tier": "featured",
    "promo": "giveaway",
    "promoLabel": "Blackhawks Toque Giveaway"
  },
  {
    "start": "2026-02-27",
    "opp": "Calgary Flames",
    "lg": "Pacific",
    "rival": false,
    "n": 1,
    "tier": "standard",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-03-05",
    "opp": "Carolina Hurricanes",
    "lg": "Metropolitan",
    "rival": false,
    "n": 1,
    "tier": "standard",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-03-10",
    "opp": "Winnipeg Jets",
    "lg": "Central",
    "rival": false,
    "n": 2,
    "tier": "select",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-03-17",
    "opp": "Colorado Avalanche",
    "lg": "Central",
    "rival": false,
    "n": 2,
    "tier": "featured",
    "promo": "theme_night",
    "promoLabel": "St. Patrick's Day Night"
  },
  {
    "start": "2026-03-24",
    "opp": "Seattle Kraken",
    "lg": "Pacific",
    "rival": false,
    "n": 1,
    "tier": "standard",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-03-28",
    "opp": "Florida Panthers",
    "lg": "Atlantic",
    "rival": false,
    "n": 1,
    "tier": "select",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-04-04",
    "opp": "Tampa Bay Lightning",
    "lg": "Atlantic",
    "rival": false,
    "n": 1,
    "tier": "standard",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-04-09",
    "opp": "Dallas Stars",
    "lg": "Central",
    "rival": false,
    "n": 1,
    "tier": "standard",
    "promo": "null",
    "promoLabel": null
  },
  {
    "start": "2026-04-14",
    "opp": "Minnesota Wild",
    "lg": "Central",
    "rival": false,
    "n": 2,
    "tier": "featured",
    "promo": "giveaway",
    "promoLabel": "Season Finale Poster Giveaway"
  }
];

// ── FAN GEOGRAPHY ─── STUB: replace with fan base data ─────────
const HOME_STATES = ["IL","WI","IN","MI","MN","OH","MO","NY","FL","PA"];
const STATE_WEIGHTS = [350,90,75,60,45,35,30,20,15,12];

if (typeof module !== 'undefined') {
  module.exports = { TEAM, BRAND, VENUE, UPCOMING_PACING, SERIES_SCHEDULE, HOME_STATES, STATE_WEIGHTS };
}
